spring.application.name=ecatlim-backend

spring.jpa.hibernate.ddl-auto=validate

spring.datasource.url=jdbc:mysql://localhost:3306/ecatlim
spring.datasource.username=admin
spring.datasource.password=password

spring.flyway.enabled=true
spring.flyway.baseline-on-migrate=false