spring.datasource.url=${DATABASE_URL:jdbc:mysql://localhost:3306/ecatlim}
spring.datasource.username=${DATABASE_USERNAME:admin}
spring.datasource.password=${DATABASE_PASSWORD:password}

jwt.secret=${JWT_SECRET:BR/vmjlI2ZCjJQBba5aFb8YnjGsfvxzqysmXPkUd6nUD9M+ThRpj1SML2txrrTGi}

ecatlim.link=${ECATLIM_LINK:http://localhost:4200}

azure.blob.connection=${BLOB_CONNECTION:DefaultEndpointsProtocol=http;AccountName=devstoreaccount1;AccountKey=Eby8vdM02xNOcqFlqUwJPLlmEtlCDXJ1OUzFT50uSRZ6IFsuFq2UVErCz4I6tq/K1SZFPTOtr/KBHBeksoGMGw==;BlobEndpoint=http://127.0.0.1:10000/devstoreaccount1}

ecatlim.rate-limit.trust-forwarded-for=false

ecatlim.reminders.enabled=false
