ALTER TABLE activity
    ADD assigned_enrollment_id INT NULL;

UPDATE activity a
    JOIN event_enrollment ee
        ON ee.user_id = a.assigned_user_id
        AND ee.event_id = a.event_id
        AND ee.lesson_block_id = a.lesson_block_id
SET a.assigned_enrollment_id = ee.id
WHERE a.assigned_user_id IS NOT NULL;

ALTER TABLE activity
    DROP FOREIGN KEY FK_ACTIVITY_ON_ASSIGNED_USER;

ALTER TABLE activity
    DROP COLUMN assigned_user_id;

ALTER TABLE activity
    ADD CONSTRAINT FK_ACTIVITY_ON_ASSIGNED_ENROLLMENT FOREIGN KEY (assigned_enrollment_id) REFERENCES event_enrollment (id) ON DELETE CASCADE;

ALTER TABLE activity_progress DROP FOREIGN KEY FK_ACTIVITYPROGRESS_ON_ACTIVITY;
ALTER TABLE activity_progress
    ADD CONSTRAINT FK_ACTIVITYPROGRESS_ON_ACTIVITY FOREIGN KEY (activity_id) REFERENCES activity (id) ON DELETE CASCADE;

ALTER TABLE file_submission DROP FOREIGN KEY FK_FILESUBMISSION_ON_ACTIVITY;
ALTER TABLE file_submission
    ADD CONSTRAINT FK_FILESUBMISSION_ON_ACTIVITY FOREIGN KEY (activity_id) REFERENCES activity (id) ON DELETE CASCADE;

ALTER TABLE forum_publication DROP FOREIGN KEY FK_FORUMPUBLICATION_ON_ACTIVITY;
ALTER TABLE forum_publication
    ADD CONSTRAINT FK_FORUMPUBLICATION_ON_ACTIVITY FOREIGN KEY (activity_id) REFERENCES activity (id) ON DELETE CASCADE;

ALTER TABLE survey_question DROP FOREIGN KEY FK_SURVEYQUESTION_ON_ACTIVITY;
ALTER TABLE survey_question
    ADD CONSTRAINT FK_SURVEYQUESTION_ON_ACTIVITY FOREIGN KEY (activity_id) REFERENCES activity (id) ON DELETE CASCADE;

ALTER TABLE survey_option DROP FOREIGN KEY FK_SURVEYOPTION_ON_QUESTION;
ALTER TABLE survey_option
    ADD CONSTRAINT FK_SURVEYOPTION_ON_QUESTION FOREIGN KEY (question_id) REFERENCES survey_question (id) ON DELETE CASCADE;

ALTER TABLE survey_response DROP FOREIGN KEY FK_SURVEYRESPONSE_ON_QUESTION;
ALTER TABLE survey_response
    ADD CONSTRAINT FK_SURVEYRESPONSE_ON_QUESTION FOREIGN KEY (question_id) REFERENCES survey_question (id) ON DELETE CASCADE;

ALTER TABLE activity_correctors DROP FOREIGN KEY fk_actcor_on_activity;
ALTER TABLE activity_correctors
    ADD CONSTRAINT fk_actcor_on_activity FOREIGN KEY (activity_id) REFERENCES activity (id) ON DELETE CASCADE;

ALTER TABLE file_upload_activity DROP FOREIGN KEY FK_FILEUPLOADACTIVITY_ON_ACTIVITY;
ALTER TABLE file_upload_activity
    ADD CONSTRAINT FK_FILEUPLOADACTIVITY_ON_ACTIVITY FOREIGN KEY (activity_id) REFERENCES activity (id) ON DELETE CASCADE;

ALTER TABLE forum_activity DROP FOREIGN KEY FK_FORUMACTIVITY_ON_ACTIVITY;
ALTER TABLE forum_activity
    ADD CONSTRAINT FK_FORUMACTIVITY_ON_ACTIVITY FOREIGN KEY (activity_id) REFERENCES activity (id) ON DELETE CASCADE;

ALTER TABLE survey_activity DROP FOREIGN KEY FK_SURVEYACTIVITY_ON_ACTIVITY;
ALTER TABLE survey_activity
    ADD CONSTRAINT FK_SURVEYACTIVITY_ON_ACTIVITY FOREIGN KEY (activity_id) REFERENCES activity (id) ON DELETE CASCADE;
